//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cl_Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbWebEventoEntities : DbContext
    {
        public dbWebEventoEntities()
            : base("name=dbWebEventoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAcesso> tbAcesso { get; set; }
        public virtual DbSet<tbArea> tbArea { get; set; }
        public virtual DbSet<tbArquivo> tbArquivo { get; set; }
        public virtual DbSet<tbEvento> tbEvento { get; set; }
        public virtual DbSet<tbInstituicao> tbInstituicao { get; set; }
        public virtual DbSet<tbPalestra> tbPalestra { get; set; }
        public virtual DbSet<tbUsuario> tbUsuario { get; set; }
        public virtual DbSet<tbAvaliacao> tbAvaliacao { get; set; }
    }
}
