//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cl_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAcesso
    {
        public tbAcesso()
        {
            this.tbUsuario = new HashSet<tbUsuario>();
        }
    
        public long tbAcesso_Id { get; set; }
        public string tbAcesso_Descrição { get; set; }
        public string tbAcesso_Nivel { get; set; }
        public Nullable<bool> tbAcesso_Ativo { get; set; }
        public Nullable<System.DateTime> tbAcesso_UpdateTime { get; set; }
    
        public virtual ICollection<tbUsuario> tbUsuario { get; set; }
    }
}
