//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cl_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArea
    {
        public tbArea()
        {
            this.tbEvento = new HashSet<tbEvento>();
            this.tbInstituicao = new HashSet<tbInstituicao>();
            this.tbPalestra = new HashSet<tbPalestra>();
        }
    
        public long tbArea_Id { get; set; }
        public string tbArea_Descricao { get; set; }
        public Nullable<bool> tbArea_Ativo { get; set; }
        public Nullable<System.DateTime> tbArea_UpdateTime { get; set; }
    
        public virtual ICollection<tbEvento> tbEvento { get; set; }
        public virtual ICollection<tbInstituicao> tbInstituicao { get; set; }
        public virtual ICollection<tbPalestra> tbPalestra { get; set; }
    }
}
