//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cl_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAvaliacao
    {
        public long tbAvaliacao_Id { get; set; }
        public string tbAvaliacao_Responsavel { get; set; }
        public Nullable<System.DateTime> tbAvaliacao_Data { get; set; }
        public string tbAvaliacao_Tipo { get; set; }
        public Nullable<decimal> tbAvaliacao_Origem { get; set; }
        public Nullable<decimal> tbAvaliacao_Objetivo { get; set; }
        public Nullable<decimal> tbAvaliacao_Clareza { get; set; }
        public Nullable<decimal> tbAvaliacao_Dominio { get; set; }
        public Nullable<decimal> tbAvaliacao_Qualidade { get; set; }
        public Nullable<decimal> tbAvaliacao_Apresentacao { get; set; }
        public Nullable<System.DateTime> tbAvaliacao_UpdateTime { get; set; }
    
        public virtual tbArquivo tbArquivo { get; set; }
    }
}
