//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cl_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbInstituicao
    {
        public long tbInstituicao_Id { get; set; }
        public string tbInstituicao_Cnpj { get; set; }
        public string tbInstituicao_Descricao { get; set; }
        public string tbInstituicao_Cep { get; set; }
        public string tbInstituicao_Bairro { get; set; }
        public string tbInstituicao_Cidade { get; set; }
        public string tbInstituicao_Estado { get; set; }
        public string tbInstituicao_Telefone { get; set; }
        public Nullable<System.DateTime> tbInstituicao_UpdateTime { get; set; }
    }
}
