//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cl_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        public tbUsuario()
        {
            this.tbArquivo = new HashSet<tbArquivo>();
            this.tbEvento = new HashSet<tbEvento>();
            this.tbPalestra = new HashSet<tbPalestra>();
        }
    
        public long tbUsuario_Id { get; set; }
        public string tbUsuario_Login { get; set; }
        public string tbUsuario_Senha { get; set; }
        public string tbUsuario_Email { get; set; }
        public Nullable<bool> tbUsuario_Ativo { get; set; }
        public Nullable<System.DateTime> tbUsuario_UpdateTime { get; set; }
    
        public virtual tbAcesso tbAcesso { get; set; }
        public virtual ICollection<tbArquivo> tbArquivo { get; set; }
        public virtual ICollection<tbEvento> tbEvento { get; set; }
        public virtual ICollection<tbPalestra> tbPalestra { get; set; }
    }
}
